crustcrawler:
  # Publish all joint states -----------------------------------
  joint_state_controller:
    type: joint_state_controller/JointStateController
    publish_rate: 60

  controller:
    type: "effort_controllers/JointTrajectoryController"
    joints:
      - joint_1
      - joint_2
      - joint_3
      - joint_4
      - joint_5
      - joint_6
    gains:
      joint_1: {p: 6.64, i: 0, d: 0}
      joint_2: {p: 6.64, i: 0, d: 0}
      joint_3: {p: 6.64, i: 0, d: 0}
      joint_4: {p: 6.64, i: 0, d: 0}
      joint_5: {p: 32, i: 0, d: 0}
      joint_6: {p: 32, i: 0, d: 0}
