crustcrawler:
  # Publish all joint states -----------------------------------
  joint_state_controller:
    type: joint_state_controller/JointStateController
    publish_rate: 60

  # Position Controllers ---------------------------------------
  joint1_controller:
    type: effort_controllers/JointEffortController
    joint: joint_1
  joint2_controller:
    type: effort_controllers/JointEffortController
    joint: joint_2
  joint3_controller:
    type: effort_controllers/JointEffortController
    joint: joint_3
  joint4_controller:
    type: effort_controllers/JointEffortController
    joint: joint_4
  joint5_controller:
    type: effort_controllers/JointEffortController
    joint: joint_5
  joint6_controller:
    type: effort_controllers/JointEffortController
    joint: joint_6
  gripper_left_controller:
    type: effort_controllers/JointEffortController
    joint: gripper_left_joint
  gripper_right_controller:
    type: effort_controllers/JointEffortController
    joint: gripper_right_joint