<?xml version="1.0"?>
<!-- This file contains handy macros for calculating inertias of different
		 objects. Taken from: https://en.wikipedia.org/wiki/List_of_moments_of_inertia -->
<robot xmlns:xacro="http://ros.org/wiki/xacro">
	<xacro:macro name="box_inertia" params="mass width length height">
		<inertial>
			<origin xyz="0 0 ${height/2}" />
			<mass value="${mass}" />
			<inertia
				ixx="${1.0/12.0 * mass * (height ** 2 + length ** 2)}" ixy="0" ixz="0"
				iyy="${1.0/12.0 * mass * (width ** 2 + length ** 2)}" iyz="0"
				izz="${1.0/12.0 * mass * (width ** 2 + height ** 2)}" />
		</inertial>
	</xacro:macro>
	<xacro:macro name="cylinder_inertia" params="mass radius height">
		<inertial>
			<origin xyz="0 0 ${height/2}" />
			<mass value="${mass}" />
			<inertia
				ixx="${1.0/12.0 * mass * (3.0 * radius ** 2 + height ** 2)}" ixy="0" ixz="0"
				iyy="${1.0/12.0 * mass * (3.0 * radius ** 2 + height ** 2)}" iyz="0"
				izz="${1.0/2.0 * mass * (radius ** 2)}" />
		</inertial>
	</xacro:macro>
</robot>
