//
// Academic License - for use in teaching, academic research, and meeting
// course requirements at degree granting institutions only.  Not for
// government, commercial, or other organizational use.
// File: gravity_forces_2_numeric.cpp
//
// MATLAB Coder version            : 3.3
// C/C++ source code generated on  : 23-Jul-2018 13:54:21
//

// Include Files
#include "rt_nonfinite.h"
#include "gravity_forces_2_numeric.h"

// Function Definitions

//
// GRAVITY_FORCES_2_NUMERIC
//     G2 = GRAVITY_FORCES_2_NUMERIC(T2,T3,T4,T5)
// Arguments    : double T2
//                double T3
//                double T4
//                double T5
//                double G2[6]
// Return Type  : void
//
void gravity_forces_2_numeric(double T2, double T3, double T4, double T5, double
  G2[6])
{
  double t2;
  double t3;
  double t4;
  double t5;
  double t6;
  double t7;
  double t8;
  double t9;

  //     This function was generated by the Symbolic Math Toolbox version 7.2.
  //     23-Jul-2018 13:27:14
  t2 = std::sin(T2);
  t3 = std::cos(T2);
  t4 = std::sin(T3);
  t5 = std::cos(T3);
  t6 = std::cos(T4);
  t7 = std::sin(T5);
  t8 = std::cos(T5);
  t9 = t2 * t4 * t7 * 0.3731890352476;
  G2[0] = 0.0;
  G2[1] = (((((((t2 * -2.0931098669844 + t9) - t2 * t5 * 1.1149865389773) - t3 *
               t4 * 1.1149865389773) - t2 * t5 * t6 * 0.45246033351035) - t3 *
             t4 * t6 * 0.45246033351035) - t3 * t5 * t7 * 0.3731890352476) - t2 *
           t5 * t6 * t8 * 0.3731890352476) - t3 * t4 * t6 * t8 * 0.3731890352476;
  G2[2] = ((((((t9 - t2 * t5 * 1.1149865389773) - t3 * t4 * 1.1149865389773) -
              t2 * t5 * t6 * 0.45246033351035) - t3 * t4 * t6 * 0.45246033351035)
            - t3 * t5 * t7 * 0.3731890352476) - t2 * t5 * t6 * t8 *
           0.3731890352476) - t3 * t4 * t6 * t8 * 0.3731890352476;
  G2[3] = std::cos(T2 + T3) * std::sin(T4) * (t8 * 760136.0 + 921601.0) *
    -4.9095035E-7;
  G2[4] = ((t2 * t5 * t8 * -0.3731890352476 - t3 * t4 * t8 * 0.3731890352476) +
           t2 * t4 * t6 * t7 * 0.3731890352476) - t3 * t5 * t6 * t7 *
    0.3731890352476;
  G2[5] = 0.0;
}

//
// File trailer for gravity_forces_2_numeric.cpp
//
// [EOF]
//
